# Generated by Django 4.0.5 on 2022-06-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doublesave',
            name='double_value',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
