# Generated by Django 4.0.5 on 2022-06-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_doublesave_double_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='doublesave',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
