# Generated by Django 4.0.5 on 2022-06-26 23:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_doublesave_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doublesave',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 26, 23, 58, 18, 696937)),
        ),
    ]
