# Generated by Django 4.0.5 on 2022-06-27 00:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_doublesave_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='doublesave',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 27, 0, 3, 37, 481775), null=True),
        ),
    ]
