# Generated by Django 4.0.5 on 2022-06-29 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_doublesave_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doublesave',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 29, 18, 35, 44, 116103), null=True),
        ),
    ]
