# Generated by Django 4.0.5 on 2022-06-29 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_doublesave_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doublesave',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 29, 18, 38, 36, 560801), null=True),
        ),
    ]
